### PR TITLE
Add instance Configured a => Configured [a]

### PR DESCRIPTION
**Pull request by basvandijk**
Hi Bryan, this would be handy.

### CODE REVIEW

**Comment by dubiousdavid** [comment]
Definitely could use this as well.

**Comment by roelvandijk** [comment]
I needed a `[Integer]` value from my config file. This patch is exactly what I needed.

Perhaps we can replace the `Configured [Char]` instance with a `Configured Char` instance to get rid of the `OverlappingInstances` extension.

**Comment by basvandijk** [comment]
@bos I think we can close this issue in favor of #12.

**Comment by co-dan** [comment]
Sorry for bumping the old thread, but is there a chance of merging this? I want to use this feature in my code

**Comment by bos** [comment]
Superseded by #12.

**Pull request closed without merging**
